services:

  # =========================
  # MySQL Database
  # =========================
  mysql:

    image: mysql:8.0

    container_name: mysql

    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password

    secrets:
      - mysql_root_password

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - app-network

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p$$(cat /run/secrets/mysql_root_password)"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  # =========================
  # Java Backend
  # =========================
  backend:

    image: my-backend:v7

    container_name: backend

    secrets:
      - mysql_root_password

    depends_on:

      mysql:
        condition: service_healthy

    networks:
      - app-network


  # =========================
  # Frontend / Nginx
  # =========================
  frontend:

    image: my-frontend:v3

    container_name: frontend

    ports:
      - "8080:80"

    depends_on:

      backend:
        condition: service_started

    networks:
      - app-network


# =========================
# Named Volume
# =========================
volumes:

  mysql-data:


# =========================
# Docker Network
# =========================
networks:

  app-network:


# =========================
# Docker Secret
# =========================
secrets:

  mysql_root_password:

    file: ./mysql_root_password.txt
