pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo "Checking out source code..."
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Installing Python dependencies..."

                sh '''

                     python3 -m venv .venv

                    .venv/bin/pip install -r Kubernetes-project/app/requirement.txt

                    .venv/bin/python --version

                    echo "Build completed successfully"
                '''
            }
        }

        stage('Test') {
            steps {
                echo "Running application test..."

                sh '''
                    .venv/bin/python -m py_compile Kubernetes-project/app/app.py

                    echo "Test completed successfully"
                '''
            }
        }

        stage('Docker Build') {
            steps {
                echo  "BUilding apllication on docker"

                sh '''
                docker build -f Kubernetes-project/docker/dockerfile -t python-app:latest Kubernetes-project
                '''
                  }
                 }
                 
        stage('Docker Push') {
            steps {
             echo "Pushing Docker image to Docker Hub..."

        withCredentials([usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USERNAME',
            passwordVariable: 'DOCKER_PASSWORD'
        )]) {
            sh '''
                echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

                docker tag python-app:latest $DOCKER_USERNAME/python-app:latest

                docker push $DOCKER_USERNAME/python-app:latest

                docker logout
            '''
        }
    }
}
    }
}

