pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo "Checking out source code..."
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Installing Python dependencies..."

                sh '''
                    pwd
                    ls -la
                    find . -name requirement.txt

                    python3 -m venv .venv

                    .venv/bin/pip install -r Kubernetes-project/app/requirement.txt

                    .venv/bin/python --version

                    echo "Build completed successfully"
                '''
            }
        }

        stage('Test') {
            steps {
                echo "Running application test..."

                sh '''
                    .venv/bin/python -m py_compile Kubernetes-project/app/app.py

                    echo "Test completed successfully"
                '''
            }
        }
    }
}
