# =========================
# Builder Stage
# =========================
FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /app

COPY pom.xml .

COPY src ./src

RUN mvn clean package


# =========================
# Runtime Stage
# =========================
FROM eclipse-temurin:17-jre

# Create a non-root user
RUN useradd -m -u 1001 appuser

WORKDIR /app

COPY --from=builder /app/target/docker-backend-1.0.jar app.jar

# Give the application user ownership of the application
RUN chown -R appuser:appuser /app

# Switch from root to non-root user
USER appuser

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
