FROM python:3.8-slim

RUN useradd --create-home --uid 1000 --shell /bin/bash appuser

WORKDIR /app

COPY app/requirement.txt .

RUN pip install --no-cache-dir -r requirement.txt

COPY app/app.py .

RUN chown -R appuser:appuser /app

USER 1000

EXPOSE 8080

CMD ["python", "app.py"]
